### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by jcaillon** [jcaillon/Oetools.Sakoe#28]
- [x] After the source build tasks, check each previous files, those which were recompiled, check the targets differences, and remove the targets needed using sourceRemover task
- [x] we also need to do that for unchanged files; use the task executor in test mode to simply get all the files built then do the same comparison with the previous built
- [x] for Compile tasks, use a boolean that indicates wether or not files received in ExecuteForFiles should be compiled or they they already are
